; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno_r4_minima

[env:uno_r4_minima]
platform = renesas-ra@1.7.0
board = uno_r4_minima
monitor_speed = 115200
framework = arduino
build_flags =
     -D uno_r4_minima
lib_deps = 
	arduino-libraries/SD@^1.2.4
	https://github.com/washiyamagiken/AGTimer_R4_Library.git

[env:rmc_ra4m1_20]
platform = https://github.com/todateman/platform-renesas-ra.git
platform_packages = framework-arduinorenesas-uno@symlink://C:\Users\todat\.platformio\packages\framework-arduinorenesas-uno-mcr_rev20
board = rmc_ra4m1_20
monitor_speed = 115200
framework = arduino
build_flags =
    -D rmc_ra4m1_20
lib_deps = 
	arduino-libraries/SD@^1.2.4
	https://github.com/washiyamagiken/AGTimer_R4_Library.git

[env:uno_r3]
platform = atmelavr
board = uno
monitor_speed = 115200
framework = arduino
lib_deps = 
	arduino-libraries/SD@^1.2.4